### ISSUE TITLE
unable to install plugin

### ISSUE THREAD

**Issue by orimdominic** [bbbco/insomnia-plugin-faker#15]
Hello @bbbco Thanks for this plugin!

On a former computer a couple of years back, I was able to install this plugin.
On a new computer recently, I cannot install it and I get the error in the screenshot
below.

Could this be as a result of Node.js <=12 support being dropped?

I'm willing to contribute to the project to fix this if you can give guidance.

Blessings!

![Screenshot from 2023-07-24 07-06-09](https://github.com/bbbco/insomnia-plugin-faker/assets/37955249/0523708c-a0fb-4d1e-b7bf-62fe53541b23)

**Comment by ksugiarto** [comment]
I got this error

![image](https://github.com/bbbco/insomnia-plugin-faker/assets/1729513/53ea0c4b-6135-4230-8b54-129cbc4a7d9a)

```
Error: Cannot find module '@faker-js/faker'
Require stack:
- C:\Users\elka\AppData\Roaming\Insomnia\plugins\insomnia-plugin-faker\index.js
- C:\Users\elka\AppData\Local\insomnia\app-8.4.0\resources\app.asar\index.html
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/renderer_init:2:5527)
    at node:internal/modules/cjs/loader:929:27
    at Function.<anonymous> (node:electron/js2c/asar_bundle:2:13327)
    at Function._load (node:electron/js2c/renderer_init:2:4757)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Users\elka\AppData\Roaming\Insomnia\plugins\insomnia-plugin-faker\index.js:1:174)
    at Object.<anonymous> (C:\Users\elka\AppData\Roaming\Insomnia\plugins\insomnia-plugin-faker\index.js:182:3)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function.<anonymous> (node:electron/js2c/asar_bundle:2:13327)
    at Function._load (node:electron/js2c/renderer_init:2:4757)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at MR (file:///C:/Users/elka/AppData/Local/insomnia/app-8.4.0/resources/app.asar/index-68eae6fb.js:57:7484)
    at bS (file:///C:/Users/elka/AppData/Local/insomnia/app-8.4.0/resources/app.asar/index-68eae6fb.js:57:8221)
    at async u (file:///C:/Users/elka/AppData/Local/insomnia/app-8.4.0/resources/app.asar/index-68eae6fb.js:1537:32445)
    at async onSubmit (file:///C:/Users/elka/AppData/Local/insomnia/app-8.4.0/resources/app.asar/index-68eae6fb.js:1539:555)
```

Latest insomnia
![image](https://github.com/bbbco/insomnia-plugin-faker/assets/1729513/09e514b7-809e-44f0-98ec-7818fd0f4210)

Latest Node
![image](https://github.com/bbbco/insomnia-plugin-faker/assets/1729513/5561857f-2e48-4d97-a31e-86d5b6d38d7d)
